name: Deploy React App to Netlify

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Change to your required Node.js version

      - name: Install Dependencies
        run: cd dataviewer && npm install  # or yarn install

      - name: Build React App
        run: cd dataviewer && npm run build  # or yarn build

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --prod --dir=build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
